blog/urls.py
from django.urls import path

from . import views
app_name = 'blog'
urlpatterns = [
     path('', views.home_page, name='home_page'),
]

my_site/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('',include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
    comment = models.CharField(max_length=180, null=True, blank=True)
    user = models.CharField(max_length=180, null=True, blank=True)


    def __str__(self):
        return self.comment

blog/views.py
from django.shortcuts import render
from .models import Comment
def home_page(request):

    if request.method == 'POST':
        comment = request.POST.get('comment')
        user = request.POST.get("username")

        comment_obj = Comment.objects.create(
        	comment=comment,
        	user=user
        )




        print(comment * 10)
        return render(request, 'blog/home_page.html', {'comment':comment_obj})

    return render(request, 'blog/home_page.html', {'test': 'Hey this is a test can you see this?'} )
    
# Create your views here.

blog/templates/blog/home_page.html
<!DOCTYPE html>
<html>
<head>
 <title>Welcome to Echo's Blog</title>
</head>
<body>
 <!--site Header -->
 <h1>Hi. I am Echo. Welcome to my blog!</h1>

 <!-- Blog Post -->
 <h2>My First Blog Post</h2>
 <p>Here is my first blog post. One day at the mall I met this fatastic picture and I reaaly want to share it with you.</p>

 <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1524453218&di=34beea5dc671fe89853ac828bd50741d&imgtype=jpg&er=1&src=http%3A%2F%2Fimg3.duitang.com%2Fuploads%2Fitem%2F201511%2F30%2F20151130203317_rZEYu.thumb.700_0.jpeg">

 <!-- Like And Comment -->
  <button>Like</button>
  <h2>Leave a Comment</h2>
  <form action="{% url 'blog:home_page' %}" method="POST">
  {% csrf_token %}
  <input type="text" placeholder="Please Enter Your username" name="username"><br><br>
  <textarea name="comment" placeholder="Please Enter Your Comment"></textarea><br>
  <input type="submit" value="Post Me!">
  </form>

  <h2>Comments</h2>
   User {{comment.user}} says: {{comment.Comment}}


 </body>
 </html>